[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "notes"
  name = "Notes"
  url = "notes"
  weight = 2

[[main]]
  identifier = "acknowledgements"
  name = "Acknowledgements"
  url = "acknowledgements"
  weight = 3

